<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { reactive } from 'vue';
import ErpLayout from '@/Layouts/ErpLayout.vue';
import type { BranchOption, PaginationMeta, StatusOption, TreasuryTransferSummary } from '@/Types/treasury';

defineOptions({ layout: ErpLayout });
const props = defineProps<{ documents: { data: TreasuryTransferSummary[]; meta: PaginationMeta }; filters: { search: string; status: string; branch_id: number | null; per_page: number }; statuses: StatusOption[]; branches: BranchOption[]; can: { create: boolean } }>();
const filters = reactive({ ...props.filters });
const apply = (page = 1): void => router.get(route('treasury-transfers.index'), { ...filters, page }, { preserveState: true, replace: true });
const amount = (v: string): string => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(v));
const remove = (id: number): void => { if (window.confirm('Delete this Treasury Transfer draft?')) router.delete(route('treasury-transfers.destroy', id)); };
</script>
<template>
<Head title="Treasury Transfers" />
<div class="space-y-6"><div class="flex justify-between gap-4"><div><h1 class="text-2xl font-semibold">Treasury Transfers</h1><p class="mt-1 text-sm text-gray-500">Cash and bank transfers across accounts and branches.</p></div><Link v-if="can.create" :href="route('treasury-transfers.create')" class="h-fit rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">New Transfer</Link></div>
<div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><div class="grid gap-4 md:grid-cols-4"><input v-model="filters.search" placeholder="Number, account, reference" class="h-11 rounded-lg border border-gray-300 bg-transparent px-3 dark:border-gray-700"/><select v-model="filters.status" class="h-11 rounded-lg border border-gray-300 bg-transparent px-3 dark:border-gray-700"><option value="">All statuses</option><option v-for="s in statuses" :key="s.value" :value="s.value">{{ s.label }}</option></select><select v-model="filters.branch_id" class="h-11 rounded-lg border border-gray-300 bg-transparent px-3 dark:border-gray-700"><option :value="null">All branches</option><option v-for="b in branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><button class="rounded-lg bg-brand-500 px-4 py-2 text-sm text-white" type="button" @click="apply()">Apply</button></div></div>
<div class="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900"><div class="overflow-x-auto"><table class="min-w-[1050px] divide-y divide-gray-200 dark:divide-gray-800"><thead class="bg-gray-50 dark:bg-white/[0.03]"><tr><th class="px-4 py-3 text-left text-xs uppercase text-gray-500">Transfer</th><th class="px-4 py-3 text-left text-xs uppercase text-gray-500">From</th><th class="px-4 py-3 text-left text-xs uppercase text-gray-500">To</th><th class="px-4 py-3 text-left text-xs uppercase text-gray-500">Date</th><th class="px-4 py-3 text-right text-xs uppercase text-gray-500">Amount</th><th class="px-4 py-3 text-left text-xs uppercase text-gray-500">Status</th><th class="px-4 py-3 text-right text-xs uppercase text-gray-500">Actions</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800"><tr v-for="d in documents.data" :key="d.id"><td class="px-4 py-3"><Link :href="route('treasury-transfers.show', d.id)" class="font-medium text-brand-600">{{ d.transfer_number ?? `Draft #${d.id}` }}</Link><p class="text-xs text-gray-500">{{ d.transfer_type_label }}</p></td><td class="px-4 py-3 text-sm">{{ d.source_account?.code }} — {{ d.source_account?.name }}<p class="text-xs text-gray-500">{{ d.source_branch?.name }}</p></td><td class="px-4 py-3 text-sm">{{ d.destination_account?.code }} — {{ d.destination_account?.name }}<p class="text-xs text-gray-500">{{ d.destination_branch?.name }}</p></td><td class="px-4 py-3 text-sm">{{ d.transfer_date }}</td><td class="px-4 py-3 text-right text-sm font-semibold">{{ d.currency_code }} {{ amount(d.amount) }}</td><td class="px-4 py-3"><span class="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium capitalize dark:bg-gray-800">{{ d.status_label }}</span></td><td class="px-4 py-3 text-right"><div class="flex justify-end gap-2"><Link v-if="d.can.update" :href="route('treasury-transfers.edit', d.id)" class="text-sm text-gray-700 dark:text-gray-300">Edit</Link><button v-if="d.can.delete" type="button" class="text-sm text-error-600" @click="remove(d.id)">Delete</button></div></td></tr><tr v-if="documents.data.length === 0"><td colspan="7" class="px-4 py-12 text-center text-sm text-gray-500">No Treasury Transfers found.</td></tr></tbody></table></div><div class="flex items-center justify-between border-t border-gray-200 px-5 py-4 text-sm dark:border-gray-800"><span>Showing {{ documents.meta.from ?? 0 }}–{{ documents.meta.to ?? 0 }} of {{ documents.meta.total }}</span><div class="flex gap-2"><button :disabled="documents.meta.current_page <= 1" class="rounded border px-3 py-1 disabled:opacity-50" @click="apply(documents.meta.current_page - 1)">Previous</button><button :disabled="documents.meta.current_page >= documents.meta.last_page" class="rounded border px-3 py-1 disabled:opacity-50" @click="apply(documents.meta.current_page + 1)">Next</button></div></div></div></div>
</template>
