<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import ErpLayout from '@/Layouts/ErpLayout.vue';
import TreasuryLifecycleActions from '@/Components/Accounting/TreasuryLifecycleActions.vue';
import type { TreasuryTransferDetail } from '@/Types/treasury';

defineOptions({ layout: ErpLayout });
const props = defineProps<{ document: TreasuryTransferDetail }>();
const amount = (v: string): string => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(v));
const remove = (): void => { if (window.confirm('Delete this Treasury Transfer draft?')) router.delete(route('treasury-transfers.destroy', props.document.id)); };
</script>
<template><Head :title="document.transfer_number ?? `Treasury Transfer #${document.id}`"/><div class="space-y-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><Link :href="route('treasury-transfers.index')" class="text-sm text-brand-600">Treasury Transfers</Link><div class="mt-2 flex items-center gap-3"><h1 class="text-2xl font-semibold">{{ document.transfer_number ?? `Draft #${document.id}` }}</h1><span class="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium dark:bg-gray-800">{{ document.status_label }}</span></div><p class="mt-1 text-sm text-gray-500">{{ document.transfer_type_label }} · Revision {{ document.revision }}</p></div><div class="flex gap-2"><Link v-if="document.can.update" :href="route('treasury-transfers.edit', document.id)" class="rounded-lg border border-gray-300 px-4 py-2 text-sm dark:border-gray-700">Edit</Link><button v-if="document.can.delete" class="rounded-lg border border-error-300 px-4 py-2 text-sm text-error-600" @click="remove">Delete</button></div></div>
<div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><TreasuryLifecycleActions :document-id="document.id" route-prefix="treasury-transfers" :status="document.status" :can="document.can"/></div>
<div class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Source</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-gray-500">Branch</dt><dd class="font-medium">{{ document.source_branch?.code }} — {{ document.source_branch?.name }}</dd><dt class="text-gray-500">Account</dt><dd class="font-medium">{{ document.source_account?.code }} — {{ document.source_account?.name }}</dd></dl></div><div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Destination</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><dt class="text-gray-500">Branch</dt><dd class="font-medium">{{ document.destination_branch?.code }} — {{ document.destination_branch?.name }}</dd><dt class="text-gray-500">Account</dt><dd class="font-medium">{{ document.destination_account?.code }} — {{ document.destination_account?.name }}</dd></dl></div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="item in [['Transfer Date', document.transfer_date], ['Posting Date', document.posting_date], ['Amount', `${document.currency_code} ${amount(document.amount)}`], ['Base Amount', amount(document.base_amount)]]" :key="String(item[0])" class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><p class="text-xs uppercase text-gray-500">{{ item[0] }}</p><p class="mt-2 font-semibold">{{ item[1] }}</p></div></div>
<div class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Reference and Notes</h2><p class="mt-4 text-sm"><b>Reference:</b> {{ document.reference ?? '—' }}</p><p class="mt-3 whitespace-pre-line text-sm text-gray-600 dark:text-gray-300">{{ document.notes ?? '—' }}</p></div><div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Accounting</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt class="text-gray-500">Posting reference</dt><dd class="break-all">{{ document.accounting_posting_reference ?? '—' }}</dd><dt class="text-gray-500">Reversal reference</dt><dd class="break-all">{{ document.accounting_reversal_reference ?? '—' }}</dd><dt class="text-gray-500">Created by</dt><dd>{{ document.created_by?.name ?? '—' }}</dd><dt class="text-gray-500">Posted by</dt><dd>{{ document.posted_by?.name ?? '—' }}</dd></dl></div></div>
<div v-if="document.cancellation_reason || document.reversal_reason" class="rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700"><b>{{ document.reversal_reason ? 'Reversal' : 'Cancellation' }} reason:</b> {{ document.reversal_reason ?? document.cancellation_reason }}</div></div></template>
