/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sales-orders.allocation.show": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.allocation.store": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.allocation.release": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.index": [],
    "dispatches.create": [],
    "dispatches.store": [],
    "dispatches.show": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.edit": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.update": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.destroy": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.post": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.reverse": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispatches.print": [
        {
            "name": "customerDispatch",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.index": [],
    "sales-invoices.create": [],
    "sales-invoices.store": [],
    "sales-invoices.show": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.edit": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.update": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.destroy": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.post": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.reverse": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-invoices.print": [
        {
            "name": "salesInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.index": [],
    "customer-receipts.create": [],
    "customer-receipts.store": [],
    "customer-receipts.show": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.edit": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.update": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.destroy": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.submit": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.return-to-draft": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.approve": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.cancel": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.post": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.reverse": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-receipts.print": [
        {
            "name": "customerReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.accounts-receivable.aging": [],
    "reports.accounts-receivable.aging.print": [],
    "reports.accounts-receivable.aging.customers.show": [
        {
            "name": "customerId",
            "required": true
        }
    ],
    "reports.accounts-receivable.aging.customers.print": [
        {
            "name": "customerId",
            "required": true
        }
    ],
    "reports.accounts-receivable.customer-statement": [],
    "reports.accounts-receivable.customer-statement.print": [],
    "reports.accounts-receivable.open-invoices": [],
    "reports.accounts-receivable.open-invoices.print": [],
    "reports.accounts-receivable.overdue-invoices": [],
    "reports.accounts-receivable.overdue-invoices.print": [],
    "sales-returns.index": [],
    "sales-returns.create": [],
    "sales-returns.store": [],
    "sales-returns.show": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.edit": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.update": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.destroy": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.submit": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.return-to-draft": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.approve": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.cancel": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.post": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.reverse": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-returns.print": [
        {
            "name": "customerCreditNote",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credits.index": [],
    "customer-credit-applications.index": [],
    "customer-credit-applications.create": [],
    "customer-credit-applications.store": [],
    "customer-credit-applications.show": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.edit": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.update": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.destroy": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.submit": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.return-to-draft": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.approve": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.post": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.cancel": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-credit-applications.reverse": [
        {
            "name": "customerCreditApplication",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.index": [],
    "customer-refunds.create": [],
    "customer-refunds.store": [],
    "customer-refunds.show": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.edit": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.update": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.destroy": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.submit": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.return-to-draft": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.approve": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.post": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.cancel": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.reverse": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-refunds.print": [
        {
            "name": "customerRefund",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.index": [],
    "customer-ar-adjustments.create": [],
    "customer-ar-adjustments.store": [],
    "customer-ar-adjustments.show": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.edit": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.update": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.destroy": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.submit": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.return-to-draft": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.approve": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.post": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.cancel": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "customer-ar-adjustments.reverse": [
        {
            "name": "customerArAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury.index": [],
    "treasury.register": [],
    "treasury-transfers.index": [],
    "treasury-transfers.create": [],
    "treasury-transfers.store": [],
    "treasury-transfers.show": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.edit": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.update": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.destroy": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.submit": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.return-to-draft": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.approve": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.post": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.cancel": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-transfers.reverse": [
        {
            "name": "treasuryTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.index": [],
    "treasury-adjustments.create": [],
    "treasury-adjustments.store": [],
    "treasury-adjustments.show": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.edit": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.update": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.destroy": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.submit": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.return-to-draft": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.approve": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.post": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.cancel": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "treasury-adjustments.reverse": [
        {
            "name": "treasuryAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-statements.index": [],
    "bank-statements.create": [],
    "bank-statements.template": [],
    "bank-statements.store": [],
    "bank-statements.show": [
        {
            "name": "bankStatement",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-statements.destroy": [
        {
            "name": "bankStatement",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.index": [],
    "bank-reconciliations.create": [],
    "bank-reconciliations.store": [],
    "bank-reconciliations.show": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.destroy": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.automatic-match": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.manual-match": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.unmatch": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        },
        {
            "name": "bankReconciliationMatch",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.ignore": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        },
        {
            "name": "bankStatementLine",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.unignore": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        },
        {
            "name": "bankStatementLine",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.refresh": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.complete": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.reverse": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-reconciliations.print": [
        {
            "name": "bankReconciliation",
            "required": true,
            "binding": "id"
        }
    ],
    "financial-control.index": [],
    "financial-control.reconciliations": [],
    "financial-control.period-close.show": [
        {
            "name": "accountingPeriod",
            "required": true,
            "binding": "id"
        }
    ],
    "financial-control.period-close.prepare": [
        {
            "name": "accountingPeriod",
            "required": true,
            "binding": "id"
        }
    ],
    "financial-control.period-close.close": [
        {
            "name": "accountingPeriod",
            "required": true,
            "binding": "id"
        }
    ],
    "financial-control.period-close.reopen": [
        {
            "name": "accountingPeriod",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.financial-statements.trial-balance": [],
    "reports.financial-statements.trial-balance.print": [],
    "reports.financial-statements.profit-and-loss": [],
    "reports.financial-statements.profit-and-loss.print": [],
    "reports.financial-statements.balance-sheet": [],
    "reports.financial-statements.balance-sheet.print": [],
    "reports.financial-statements.cash-flow": [],
    "reports.financial-statements.cash-flow.print": [],
    "management.index": [],
    "management.budgets.index": [],
    "management.budgets.create": [],
    "management.budgets.store": [],
    "management.budgets.edit": [
        {
            "name": "managementBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "management.budgets.show": [
        {
            "name": "managementBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "management.budgets.update": [
        {
            "name": "managementBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "management.budgets.destroy": [
        {
            "name": "managementBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "management.budgets.approve": [
        {
            "name": "managementBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "management.budgets.reopen": [
        {
            "name": "managementBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "management.reports.branch-profitability": [],
    "management.reports.budget-vs-actual": [],
    "management.reports.product-profitability": [],
    "management.reports.customer-profitability": [],
    "management.reports.supplier-spend": [],
    "management.reports.gross-margin": [],
    "management.schedules.index": [],
    "management.schedules.store": [],
    "management.schedules.toggle": [
        {
            "name": "managementReportSchedule",
            "required": true,
            "binding": "id"
        }
    ],
    "management.schedules.destroy": [
        {
            "name": "managementReportSchedule",
            "required": true,
            "binding": "id"
        }
    ],
    "management.production-readiness": [],
    "operations.index": [],
    "operations.backups.index": [],
    "operations.backups.verify": [
        {
            "name": "systemBackup",
            "required": true,
            "binding": "id"
        }
    ],
    "operations.failed-jobs.index": [],
    "operations.preflight": [],
    "production-acceptance.index": [],
    "production-acceptance.store": [],
    "production-acceptance.show": [
        {
            "name": "productionAcceptanceRun",
            "required": true,
            "binding": "id"
        }
    ],
    "release-candidates.index": [],
    "release-candidates.store": [],
    "release-candidates.show": [
        {
            "name": "releaseCandidate",
            "required": true,
            "binding": "id"
        }
    ],
    "release-candidates.verify": [
        {
            "name": "releaseCandidate",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "login.store": [],
    "dashboard": [],
    "company-settings.edit": [],
    "company-settings.update": [],
    "branches.index": [],
    "branches.create": [],
    "branches.store": [],
    "branches.edit": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "branches.update": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "branches.destroy": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "warehouses.index": [],
    "warehouses.create": [],
    "warehouses.store": [],
    "warehouses.edit": [
        {
            "name": "warehouse",
            "required": true,
            "binding": "id"
        }
    ],
    "warehouses.update": [
        {
            "name": "warehouse",
            "required": true,
            "binding": "id"
        }
    ],
    "warehouses.destroy": [
        {
            "name": "warehouse",
            "required": true,
            "binding": "id"
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.edit": [
        {
            "name": "managedUser",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "managedUser",
            "required": true,
            "binding": "id"
        }
    ],
    "users.change-status": [
        {
            "name": "managedUser",
            "required": true,
            "binding": "id"
        }
    ],
    "users.reset-password": [
        {
            "name": "managedUser",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "managedUser",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.index": [],
    "roles.create": [],
    "roles.store": [],
    "roles.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.sync-permissions": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "document-numbering.index": [],
    "document-numbering.create": [],
    "document-numbering.store": [],
    "document-numbering.edit": [
        {
            "name": "documentSequence",
            "required": true,
            "binding": "id"
        }
    ],
    "document-numbering.update": [
        {
            "name": "documentSequence",
            "required": true,
            "binding": "id"
        }
    ],
    "document-numbering.destroy": [
        {
            "name": "documentSequence",
            "required": true,
            "binding": "id"
        }
    ],
    "accounting-periods.index": [],
    "accounting-periods.create": [],
    "accounting-periods.store": [],
    "accounting-periods.periods.close": [
        {
            "name": "accountingPeriod",
            "required": true,
            "binding": "id"
        }
    ],
    "accounting-periods.periods.reopen": [
        {
            "name": "accountingPeriod",
            "required": true,
            "binding": "id"
        }
    ],
    "accounting-periods.show": [
        {
            "name": "fiscalYear",
            "required": true,
            "binding": "id"
        }
    ],
    "audit-logs.index": [],
    "audit-logs.show": [
        {
            "name": "auditLog",
            "required": true,
            "binding": "id"
        }
    ],
    "exports.index": [],
    "exports.store": [],
    "exports.download": [
        {
            "name": "exportRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "exports.cancel": [
        {
            "name": "exportRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "notifications.index": [],
    "notifications.read-all": [],
    "notifications.read": [
        {
            "name": "userNotification",
            "required": true,
            "binding": "id"
        }
    ],
    "files.store": [],
    "files.download": [
        {
            "name": "tenantFile",
            "required": true,
            "binding": "id"
        }
    ],
    "files.destroy": [
        {
            "name": "tenantFile",
            "required": true,
            "binding": "id"
        }
    ],
    "units.index": [],
    "units.create": [],
    "units.store": [],
    "units.edit": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "units.update": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "units.destroy": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "product-categories.index": [],
    "product-categories.create": [],
    "product-categories.store": [],
    "product-categories.edit": [
        {
            "name": "productCategory",
            "required": true,
            "binding": "id"
        }
    ],
    "product-categories.update": [
        {
            "name": "productCategory",
            "required": true,
            "binding": "id"
        }
    ],
    "product-categories.destroy": [
        {
            "name": "productCategory",
            "required": true,
            "binding": "id"
        }
    ],
    "brands.index": [],
    "brands.create": [],
    "brands.store": [],
    "brands.edit": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "brands.update": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "brands.destroy": [
        {
            "name": "brand",
            "required": true,
            "binding": "id"
        }
    ],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.locations.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.locations.branches.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.locations.warehouses.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.locations.branches.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "productBranchSetting",
            "required": true,
            "binding": "id"
        }
    ],
    "products.locations.warehouses.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "productWarehouseSetting",
            "required": true,
            "binding": "id"
        }
    ],
    "suppliers.index": [],
    "suppliers.create": [],
    "suppliers.store": [],
    "suppliers.edit": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "suppliers.update": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "suppliers.destroy": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.index": [],
    "customers.create": [],
    "customers.store": [],
    "customers.edit": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.index": [],
    "purchase-orders.create": [],
    "purchase-orders.store": [],
    "purchase-orders.show": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.edit": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.update": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.destroy": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.submit": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.return-to-draft": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.approve": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.cancel": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.index": [],
    "sales-orders.create": [],
    "sales-orders.store": [],
    "sales-orders.show": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.edit": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.update": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.destroy": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.submit": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.return-to-draft": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.approve": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-orders.cancel": [
        {
            "name": "salesOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "goods-receipts.index": [],
    "goods-receipts.create": [],
    "goods-receipts.store": [],
    "goods-receipts.show": [
        {
            "name": "goodsReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "goods-receipts.edit": [
        {
            "name": "goodsReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "goods-receipts.update": [
        {
            "name": "goodsReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "goods-receipts.destroy": [
        {
            "name": "goodsReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "goods-receipts.post": [
        {
            "name": "goodsReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "goods-receipts.reverse": [
        {
            "name": "goodsReceipt",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.index": [],
    "supplier-invoices.create": [],
    "supplier-invoices.store": [],
    "supplier-invoices.show": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.edit": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.update": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.destroy": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.validate": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.return-to-draft": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.approve": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.dispute": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.cancel": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.post": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-invoices.reverse": [
        {
            "name": "supplierInvoice",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.index": [],
    "purchase-returns.create": [],
    "purchase-returns.store": [],
    "purchase-returns.show": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.edit": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.update": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.destroy": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.submit": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.return-to-draft": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.approve": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.cancel": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.post": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-returns.reverse": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.index": [],
    "supplier-debit-notes.create": [],
    "supplier-debit-notes.store": [],
    "supplier-debit-notes.show": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.edit": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.update": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.destroy": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.submit": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.return-to-draft": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.approve": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.cancel": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.post": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-debit-notes.reverse": [
        {
            "name": "supplierDebitNote",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.index": [],
    "supplier-payments.create": [],
    "supplier-payments.store": [],
    "supplier-payments.show": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.edit": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.update": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.destroy": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.submit": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.return-to-draft": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.approve": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.cancel": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.post": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "supplier-payments.reverse": [
        {
            "name": "supplierPayment",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.accounts-payable.aging": [],
    "reports.accounts-payable.aging.suppliers.show": [
        {
            "name": "supplierId",
            "required": true
        }
    ],
    "reports.accounts-payable.supplier-statement": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
