<script setup lang="ts">
import { Head, router, useForm } from '@inertiajs/vue3';
import { computed } from 'vue';
import { useAuthorization } from '@/Composables/useAuthorization';
import ErpLayout from '@/Layouts/ErpLayout.vue';
import type { ManagementBranch, ManagementSchedule } from '@/Types/management';

defineOptions({ layout: ErpLayout });
const props = defineProps<{
    schedules: ManagementSchedule[];
    branches: ManagementBranch[];
    budgets: Array<{ id: number; name: string; branch_name: string | null; fiscal_year_name: string | null }>;
    reportTypes: Array<{ value: string; label: string }>;
}>();
const { can } = useAuthorization();
const form = useForm({ name: '', report_type: 'management_branch_profitability', format: 'xlsx', frequency: 'monthly', run_day: 1 as number | null, run_time: '07:00', branch_id: null as number | null, budget_id: null as number | null, limit: 100, date_window_days: 30 });
const budgetRequired = computed(() => form.report_type === 'management_budget_vs_actual');
const submit = (): void => form.post(route('management.schedules.store'), { preserveScroll: true, onSuccess: () => form.reset('name') });
const toggle = (schedule: ManagementSchedule): void => { if (window.confirm(`${schedule.status === 'active' ? 'Pause' : 'Activate'} this schedule?`)) router.post(route('management.schedules.toggle', schedule.id), {}, { preserveScroll: true }); };
const remove = (schedule: ManagementSchedule): void => { if (window.confirm('Delete this scheduled report?')) router.delete(route('management.schedules.destroy', schedule.id), { preserveScroll: true }); };
const label = (type: string): string => props.reportTypes.find((item) => item.value === type)?.label ?? type;
</script>
<template>
    <Head title="Scheduled Management Reports" />
    <div class="space-y-5">
        <div><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">Scheduled Management Reports</h1><p class="text-sm text-gray-500">Queue recurring CSV or Excel outputs into the tenant Export Center.</p></div>
        <form v-if="can('management_report_schedules.create')" class="grid gap-3 rounded-xl border p-4 md:grid-cols-4 dark:border-gray-800" @submit.prevent="submit"><input v-model="form.name" required maxlength="160" placeholder="Schedule name" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900" /><select v-model="form.report_type" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900"><option v-for="item in reportTypes" :key="item.value" :value="item.value">{{ item.label }}</option></select><select v-model="form.format" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900"><option value="xlsx">Excel</option><option value="csv">CSV</option></select><select v-model="form.frequency" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><select v-model="form.branch_id" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900"><option :value="null">All accessible branches</option><option v-for="branch in branches" :key="branch.id" :value="branch.id">{{ branch.code }} — {{ branch.name }}</option></select><select v-if="budgetRequired" v-model="form.budget_id" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900"><option :value="null">Select budget</option><option v-for="budget in budgets" :key="budget.id" :value="budget.id">{{ budget.branch_name }} — {{ budget.name }}</option></select><input v-if="form.frequency !== 'daily'" v-model="form.run_day" type="number" min="1" :max="form.frequency === 'weekly' ? 7 : 28" :placeholder="form.frequency === 'weekly' ? 'ISO weekday 1–7' : 'Day 1–28'" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900" /><input v-model="form.run_time" type="time" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900" /><input v-if="!budgetRequired" v-model="form.date_window_days" type="number" min="1" max="366" title="Rolling report window in days" class="rounded-lg border-gray-300 dark:border-gray-700 dark:bg-gray-900" /><button type="submit" :disabled="form.processing" class="rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Create schedule</button><div v-if="Object.keys(form.errors).length" class="md:col-span-4 text-sm text-error-600">{{ Object.values(form.errors)[0] }}</div></form>
        <div class="overflow-hidden rounded-xl border dark:border-gray-800"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-white/5"><tr><th class="p-3">Schedule</th><th class="p-3">Report</th><th class="p-3">Frequency</th><th class="p-3">Next run</th><th class="p-3">Last result</th><th class="p-3 text-right">Actions</th></tr></thead><tbody><tr v-for="schedule in schedules" :key="schedule.id" class="border-t dark:border-gray-800"><td class="p-3"><p class="font-medium">{{ schedule.name }}</p><p class="text-xs text-gray-500">{{ schedule.branch?.name ?? 'All accessible branches' }} · {{ schedule.format.toUpperCase() }} · {{ schedule.status }}</p></td><td class="p-3">{{ label(schedule.report_type) }}</td><td class="p-3 capitalize">{{ schedule.frequency }}<span v-if="schedule.run_day"> · {{ schedule.run_day }}</span> · {{ schedule.run_time }}</td><td class="p-3">{{ schedule.next_run_at ?? 'Paused' }}</td><td class="p-3"><span>{{ schedule.last_status ?? 'Never run' }}</span><p v-if="schedule.last_error" class="max-w-xs text-xs text-error-600">{{ schedule.last_error }}</p></td><td class="p-3 text-right"><button v-if="can('management_report_schedules.update')" class="text-brand-600" @click="toggle(schedule)">{{ schedule.status === 'active' ? 'Pause' : 'Activate' }}</button><button v-if="can('management_report_schedules.delete')" class="ml-3 text-error-600" @click="remove(schedule)">Delete</button></td></tr><tr v-if="schedules.length === 0"><td colspan="6" class="p-8 text-center text-gray-500">No recurring management reports configured.</td></tr></tbody></table></div></div>
    </div>
</template>
