<?php

declare(strict_types=1);

namespace App\Support\Accounting;

final class DefaultChartOfAccounts
{
    /**
     * @var list<array{
     *     code: string,
     *     name: string,
     *     parent_code: string|null,
     *     account_type: string,
     *     account_subtype: string|null,
     *     system_key: string|null,
     *     is_group: bool,
     *     allow_manual_posting: bool,
     *     description: string
     * }>
     */
    private const DEFINITIONS = [
        [
            'code' => '1000',
            'name' => 'Assets',
            'parent_code' => null,
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Root account for assets controlled by the tenant.',
        ],
        [
            'code' => '1100',
            'name' => 'Current Assets',
            'parent_code' => '1000',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Assets expected to be realized, sold, or consumed in the normal operating cycle.',
        ],
        [
            'code' => '1110',
            'name' => 'Cash and Cash Equivalents',
            'parent_code' => '1100',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for cash-on-hand and bank balances.',
        ],
        [
            'code' => '1111',
            'name' => 'Cash Control',
            'parent_code' => '1110',
            'account_type' => 'asset',
            'account_subtype' => 'cash',
            'system_key' => 'cash_control',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Protected control account used by system cash transactions.',
        ],
        [
            'code' => '1112',
            'name' => 'Bank Control',
            'parent_code' => '1110',
            'account_type' => 'asset',
            'account_subtype' => 'bank',
            'system_key' => 'bank_control',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Protected control account used by system bank transactions.',
        ],
        [
            'code' => '1120',
            'name' => 'Trade and Other Receivables',
            'parent_code' => '1100',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for customer and other short-term receivables.',
        ],
        [
            'code' => '1121',
            'name' => 'Accounts Receivable Control',
            'parent_code' => '1120',
            'account_type' => 'asset',
            'account_subtype' => 'accounts_receivable',
            'system_key' => 'accounts_receivable_control',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Protected customer-subledger control account.',
        ],
        [
            'code' => '1130',
            'name' => 'Inventory and Purchasing Assets',
            'parent_code' => '1100',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for inventory, recoverable purchase taxes, and related current assets.',
        ],
        [
            'code' => '1131',
            'name' => 'Inventory Asset',
            'parent_code' => '1130',
            'account_type' => 'asset',
            'account_subtype' => 'inventory',
            'system_key' => 'inventory_asset',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Protected control account for perpetual inventory value.',
        ],
        [
            'code' => '1132',
            'name' => 'Input Tax Receivable',
            'parent_code' => '1130',
            'account_type' => 'asset',
            'account_subtype' => 'input_tax',
            'system_key' => 'input_tax_receivable',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Recoverable input tax arising from purchases and expenses.',
        ],
        [
            'code' => '1140',
            'name' => 'Advances and Prepayments',
            'parent_code' => '1100',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for supplier advances, prepaid expenses, and other prepayments.',
        ],
        [
            'code' => '1141',
            'name' => 'Supplier Advances',
            'parent_code' => '1140',
            'account_type' => 'asset',
            'account_subtype' => 'supplier_advances',
            'system_key' => 'supplier_advances',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Protected supplier-subledger account for payments made before payable recognition.',
        ],
        [
            'code' => '1142',
            'name' => 'Prepaid Expenses',
            'parent_code' => '1140',
            'account_type' => 'asset',
            'account_subtype' => 'prepaid_expense',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Expenses paid before the related benefit is consumed.',
        ],
        [
            'code' => '1200',
            'name' => 'Non-current Assets',
            'parent_code' => '1000',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Assets expected to provide benefits beyond the current operating cycle.',
        ],
        [
            'code' => '1210',
            'name' => 'Property, Plant and Equipment',
            'parent_code' => '1200',
            'account_type' => 'asset',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for tangible fixed assets and related accumulated depreciation.',
        ],
        [
            'code' => '1211',
            'name' => 'Office Equipment',
            'parent_code' => '1210',
            'account_type' => 'asset',
            'account_subtype' => 'fixed_asset',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Cost of office equipment owned by the tenant.',
        ],
        [
            'code' => '1212',
            'name' => 'Furniture and Fixtures',
            'parent_code' => '1210',
            'account_type' => 'asset',
            'account_subtype' => 'fixed_asset',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Cost of furniture and fixtures owned by the tenant.',
        ],
        [
            'code' => '1219',
            'name' => 'Accumulated Depreciation',
            'parent_code' => '1210',
            'account_type' => 'asset',
            'account_subtype' => 'accumulated_depreciation',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Contra-asset account for accumulated depreciation.',
        ],
        [
            'code' => '2000',
            'name' => 'Liabilities',
            'parent_code' => null,
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Root account for present obligations of the tenant.',
        ],
        [
            'code' => '2100',
            'name' => 'Current Liabilities',
            'parent_code' => '2000',
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Obligations expected to be settled in the normal operating cycle.',
        ],
        [
            'code' => '2110',
            'name' => 'Trade and Other Payables',
            'parent_code' => '2100',
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for supplier payables and purchasing accruals.',
        ],
        [
            'code' => '2111',
            'name' => 'Accounts Payable Control',
            'parent_code' => '2110',
            'account_type' => 'liability',
            'account_subtype' => 'accounts_payable',
            'system_key' => 'accounts_payable_control',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Protected supplier-subledger control account.',
        ],
        [
            'code' => '2112',
            'name' => 'Goods Received Not Invoiced',
            'parent_code' => '2110',
            'account_type' => 'liability',
            'account_subtype' => 'goods_received_not_invoiced',
            'system_key' => 'goods_received_not_invoiced',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Accrual for received inventory awaiting supplier invoicing.',
        ],
        [
            'code' => '2120',
            'name' => 'Taxes and Statutory Payables',
            'parent_code' => '2100',
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for output tax and other statutory obligations.',
        ],
        [
            'code' => '2121',
            'name' => 'Output Tax Payable',
            'parent_code' => '2120',
            'account_type' => 'liability',
            'account_subtype' => 'output_tax',
            'system_key' => 'output_tax_payable',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'Output tax collected and payable to the relevant authority.',
        ],
        [
            'code' => '2130',
            'name' => 'Accruals and Other Current Liabilities',
            'parent_code' => '2100',
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for accrued and miscellaneous current obligations.',
        ],
        [
            'code' => '2131',
            'name' => 'Accrued Expenses',
            'parent_code' => '2130',
            'account_type' => 'liability',
            'account_subtype' => 'accrued_liability',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Expenses recognized before payment or supplier invoicing.',
        ],
        [
            'code' => '2200',
            'name' => 'Non-current Liabilities',
            'parent_code' => '2000',
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Obligations expected to remain outstanding beyond the current operating cycle.',
        ],
        [
            'code' => '2210',
            'name' => 'Borrowings',
            'parent_code' => '2200',
            'account_type' => 'liability',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for long-term loans and other non-current borrowings.',
        ],
        [
            'code' => '2211',
            'name' => 'Long-term Loans',
            'parent_code' => '2210',
            'account_type' => 'liability',
            'account_subtype' => 'loan',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Principal outstanding on long-term financing arrangements.',
        ],
        [
            'code' => '3000',
            'name' => 'Equity',
            'parent_code' => null,
            'account_type' => 'equity',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Root account for residual ownership interest in the tenant.',
        ],
        [
            'code' => '3100',
            'name' => 'Contributed Capital',
            'parent_code' => '3000',
            'account_type' => 'equity',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for capital contributed by owners or shareholders.',
        ],
        [
            'code' => '3110',
            'name' => 'Share Capital',
            'parent_code' => '3100',
            'account_type' => 'equity',
            'account_subtype' => 'share_capital',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Issued capital contributed by owners or shareholders.',
        ],
        [
            'code' => '3200',
            'name' => 'Retained Earnings',
            'parent_code' => '3000',
            'account_type' => 'equity',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for accumulated profits and losses retained by the tenant.',
        ],
        [
            'code' => '3210',
            'name' => 'Retained Earnings',
            'parent_code' => '3200',
            'account_type' => 'equity',
            'account_subtype' => 'retained_earnings',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Accumulated earnings retained after distributions.',
        ],
        [
            'code' => '3300',
            'name' => 'Reserves',
            'parent_code' => '3000',
            'account_type' => 'equity',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for general and designated equity reserves.',
        ],
        [
            'code' => '3310',
            'name' => 'General Reserve',
            'parent_code' => '3300',
            'account_type' => 'equity',
            'account_subtype' => 'reserves',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'General reserve appropriated from retained earnings.',
        ],
        [
            'code' => '4000',
            'name' => 'Revenue',
            'parent_code' => null,
            'account_type' => 'revenue',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Root account for income earned by the tenant.',
        ],
        [
            'code' => '4100',
            'name' => 'Operating Revenue',
            'parent_code' => '4000',
            'account_type' => 'revenue',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Revenue arising from the tenant’s primary operating activities.',
        ],
        [
            'code' => '4110',
            'name' => 'Sales Revenue',
            'parent_code' => '4100',
            'account_type' => 'revenue',
            'account_subtype' => 'sales_revenue',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Revenue from the sale of goods.',
        ],
        [
            'code' => '4120',
            'name' => 'Service Revenue',
            'parent_code' => '4100',
            'account_type' => 'revenue',
            'account_subtype' => 'service_revenue',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Revenue from services provided to customers.',
        ],
        [
            'code' => '4200',
            'name' => 'Other Income',
            'parent_code' => '4000',
            'account_type' => 'revenue',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Income not arising directly from primary operating activities.',
        ],
        [
            'code' => '4210',
            'name' => 'Realized Exchange Gain',
            'parent_code' => '4200',
            'account_type' => 'revenue',
            'account_subtype' => 'other_income',
            'system_key' => 'realized_exchange_gain',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'System-recognized gain from settling foreign-currency balances.',
        ],
        [
            'code' => '4220',
            'name' => 'Other Income',
            'parent_code' => '4200',
            'account_type' => 'revenue',
            'account_subtype' => 'other_income',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Miscellaneous income not separately classified.',
        ],
        [
            'code' => '5000',
            'name' => 'Expenses',
            'parent_code' => null,
            'account_type' => 'expense',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Root account for costs and expenses incurred by the tenant.',
        ],
        [
            'code' => '5100',
            'name' => 'Cost of Sales and Purchase Adjustments',
            'parent_code' => '5000',
            'account_type' => 'expense',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Group for cost of sales and purchase-related value adjustments.',
        ],
        [
            'code' => '5110',
            'name' => 'Cost of Goods Sold',
            'parent_code' => '5100',
            'account_type' => 'expense',
            'account_subtype' => 'cost_of_sales',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Cost assigned to inventory sold during the period.',
        ],
        [
            'code' => '5120',
            'name' => 'Purchase Return Recovery',
            'parent_code' => '5100',
            'account_type' => 'expense',
            'account_subtype' => 'purchase_returns',
            'system_key' => 'purchase_return_recovery',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'System account for supplier value recovered through purchase returns and debit notes.',
        ],
        [
            'code' => '5130',
            'name' => 'Purchase Price Variance',
            'parent_code' => '5100',
            'account_type' => 'expense',
            'account_subtype' => 'purchase_price_variance',
            'system_key' => 'purchase_price_variance',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'System account for differences between purchasing and inventory valuation amounts.',
        ],
        [
            'code' => '5140',
            'name' => 'Non-stock Purchases and Services Expense',
            'parent_code' => '5100',
            'account_type' => 'expense',
            'account_subtype' => 'non_stock_purchase',
            'system_key' => 'non_stock_purchase_expense',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'System account for accepted non-stock purchases and services recognized at Goods Receipt.',
        ],
        [
            'code' => '5200',
            'name' => 'Operating Expenses',
            'parent_code' => '5000',
            'account_type' => 'expense',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Expenses arising from day-to-day operating activities.',
        ],
        [
            'code' => '5210',
            'name' => 'General and Administrative Expenses',
            'parent_code' => '5200',
            'account_type' => 'expense',
            'account_subtype' => 'operating_expense',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'General office and administrative operating expenses.',
        ],
        [
            'code' => '5220',
            'name' => 'Selling and Distribution Expenses',
            'parent_code' => '5200',
            'account_type' => 'expense',
            'account_subtype' => 'operating_expense',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Expenses incurred to market, sell, and distribute goods or services.',
        ],
        [
            'code' => '5230',
            'name' => 'Depreciation Expense',
            'parent_code' => '5200',
            'account_type' => 'expense',
            'account_subtype' => 'depreciation_expense',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Periodic allocation of depreciable asset cost.',
        ],
        [
            'code' => '5300',
            'name' => 'Finance and Other Expenses',
            'parent_code' => '5000',
            'account_type' => 'expense',
            'account_subtype' => null,
            'system_key' => null,
            'is_group' => true,
            'allow_manual_posting' => false,
            'description' => 'Finance costs, exchange losses, taxes, and miscellaneous expenses.',
        ],
        [
            'code' => '5310',
            'name' => 'Finance Costs',
            'parent_code' => '5300',
            'account_type' => 'expense',
            'account_subtype' => 'finance_cost',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Interest, financing fees, and related borrowing costs.',
        ],
        [
            'code' => '5320',
            'name' => 'Realized Exchange Loss',
            'parent_code' => '5300',
            'account_type' => 'expense',
            'account_subtype' => 'exchange_loss',
            'system_key' => 'realized_exchange_loss',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'System-recognized loss from settling foreign-currency balances.',
        ],
        [
            'code' => '5330',
            'name' => 'Rounding Difference',
            'parent_code' => '5300',
            'account_type' => 'expense',
            'account_subtype' => 'other_expense',
            'system_key' => 'rounding_difference',
            'is_group' => false,
            'allow_manual_posting' => false,
            'description' => 'System account for immaterial rounding differences in balanced postings.',
        ],
        [
            'code' => '5340',
            'name' => 'Tax Expense',
            'parent_code' => '5300',
            'account_type' => 'expense',
            'account_subtype' => 'tax_expense',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Income and other non-recoverable tax expense.',
        ],
        [
            'code' => '5350',
            'name' => 'Other Expenses',
            'parent_code' => '5300',
            'account_type' => 'expense',
            'account_subtype' => 'other_expense',
            'system_key' => null,
            'is_group' => false,
            'allow_manual_posting' => true,
            'description' => 'Miscellaneous expenses not separately classified.',
        ],
    ];

    /**
     * @return list<array{
     *     code: string,
     *     name: string,
     *     parent_code: string|null,
     *     account_type: string,
     *     account_subtype: string|null,
     *     system_key: string|null,
     *     is_group: bool,
     *     allow_manual_posting: bool,
     *     description: string
     * }>
     */
    public function definitions(): array
    {
        return self::DEFINITIONS;
    }
}