<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import {
    nextTick,
    onMounted,
} from 'vue';

interface PrintTenant {
    name: string;
    code: string;
    email: string | null;
    phone: string | null;
    address: string | null;
    currency_code: string;
    timezone: string;
}

interface PrintGeneratedBy {
    id: number;
    name: string;
    email: string;
}

interface Props {
    title: string;
    tenant: PrintTenant;
    generatedBy: PrintGeneratedBy;
    generatedAt: string;
    autoprint?: boolean;
}

const props = withDefaults(
    defineProps<Props>(),
    {
        autoprint: false,
    },
);

const printDocument = (): void => {
    window.print();
};

const closeWindow = (): void => {
    window.close();
};

onMounted(
    async (): Promise<void> => {
        if (!props.autoprint) {
            return;
        }

        await nextTick();

        window.requestAnimationFrame(
            (): void => {
                window.requestAnimationFrame(
                    (): void => {
                        window.print();
                    },
                );
            },
        );
    },
);
</script>

<template>
    <Head :title="title" />

    <div class="ap-print-page">
        <div class="ap-print-toolbar">
            <button
                type="button"
                class="ap-print-button"
                @click="closeWindow"
            >
                Close
            </button>

            <button
                type="button"
                class="ap-print-button ap-print-button-primary"
                @click="printDocument"
            >
                Print / Save PDF
            </button>
        </div>

        <main class="ap-print-document">
            <header class="ap-print-header">
                <div>
                    <h1 class="ap-print-company-name">
                        {{ tenant.name }}
                    </h1>

                    <div class="ap-print-company-meta">
                        <div>
                            Company code:
                            {{ tenant.code }}
                        </div>

                        <div v-if="tenant.address">
                            {{ tenant.address }}
                        </div>

                        <div
                            v-if="
                                tenant.email
                                || tenant.phone
                            "
                        >
                            <span v-if="tenant.email">
                                {{ tenant.email }}
                            </span>

                            <span
                                v-if="
                                    tenant.email
                                    && tenant.phone
                                "
                            >
                                ·
                            </span>

                            <span v-if="tenant.phone">
                                {{ tenant.phone }}
                            </span>
                        </div>
                    </div>
                </div>

                <div class="ap-print-generated-meta">
                    <div>
                        <strong>Generated:</strong>
                        {{ generatedAt }}
                    </div>

                    <div>
                        <strong>Generated by:</strong>
                        {{ generatedBy.name }}
                    </div>

                    <div>
                        <strong>User:</strong>
                        {{ generatedBy.email }}
                    </div>
                </div>
            </header>

            <slot />

            <footer class="ap-print-footer">
                <span>
                    Confidential tenant financial report
                </span>

                <span>
                    Base currency:
                    {{ tenant.currency_code }}
                    · Timezone:
                    {{ tenant.timezone }}
                </span>
            </footer>
        </main>
    </div>
</template>

<style>
:root {
    color-scheme: light;
}

.ap-print-page {
    min-height: 100vh;
    margin: 0;
    padding: 24px;
    background: #f3f4f6;
    color: #111827;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12px;
}

.ap-print-page,
.ap-print-page * {
    box-sizing: border-box;
}

.ap-print-toolbar {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
    width: min(100%, 1440px);
    margin: 0 auto 12px;
}

.ap-print-button {
    cursor: pointer;
    border: 1px solid #9ca3af;
    border-radius: 6px;
    padding: 8px 14px;
    background: #ffffff;
    color: #111827;
    font: inherit;
    font-weight: 600;
}

.ap-print-button:hover {
    background: #f9fafb;
}

.ap-print-button-primary {
    border-color: #2563eb;
    background: #2563eb;
    color: #ffffff;
}

.ap-print-button-primary:hover {
    background: #1d4ed8;
}

.ap-print-document {
    width: min(100%, 1440px);
    margin: 0 auto;
    border: 1px solid #d1d5db;
    padding: 28px;
    background: #ffffff;
    box-shadow: 0 8px 30px rgb(15 23 42 / 8%);
}

.ap-print-header {
    display: flex;
    justify-content: space-between;
    gap: 24px;
    border-bottom: 2px solid #111827;
    padding-bottom: 18px;
}

.ap-print-company-name {
    margin: 0;
    font-size: 22px;
    line-height: 1.25;
}

.ap-print-company-meta,
.ap-print-generated-meta {
    margin-top: 6px;
    color: #4b5563;
    line-height: 1.55;
}

.ap-print-generated-meta {
    text-align: right;
}

.ap-print-report-title {
    margin: 22px 0 6px;
    font-size: 20px;
    line-height: 1.25;
}

.ap-print-report-subtitle {
    margin: 0 0 18px;
    color: #4b5563;
}

.ap-print-summary-grid {
    display: grid;
    grid-template-columns: repeat(
        3,
        minmax(0, 1fr)
    );
    gap: 10px;
    margin: 16px 0;
}

.ap-print-summary-grid-six {
    grid-template-columns: repeat(
        6,
        minmax(0, 1fr)
    );
}

.ap-print-summary-card {
    break-inside: avoid;
    border: 1px solid #d1d5db;
    border-radius: 6px;
    padding: 12px;
}

.ap-print-summary-label {
    color: #6b7280;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
}

.ap-print-summary-value {
    margin-top: 6px;
    font-size: 16px;
    font-weight: 700;
}

.ap-print-section-title {
    margin: 20px 0 8px;
    font-size: 14px;
}

.ap-print-table-wrapper {
    width: 100%;
    overflow-x: auto;
}

.ap-print-table {
    width: 100%;
    border-collapse: collapse;
    page-break-inside: auto;
}

.ap-print-table thead {
    display: table-header-group;
}

.ap-print-table tr {
    page-break-inside: avoid;
    page-break-after: auto;
}

.ap-print-table th,
.ap-print-table td {
    border: 1px solid #d1d5db;
    padding: 7px 6px;
    vertical-align: top;
}

.ap-print-table th {
    background: #f3f4f6;
    color: #374151;
    font-size: 9px;
    letter-spacing: 0.04em;
    text-align: left;
    text-transform: uppercase;
}

.ap-print-number {
    text-align: right !important;
    white-space: nowrap;
}

.ap-print-muted {
    color: #6b7280;
}

.ap-print-credit {
    color: #047857;
}

.ap-print-payable {
    color: #b91c1c;
}

.ap-print-empty {
    padding: 20px !important;
    color: #6b7280;
    text-align: center;
}

.ap-print-footer {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    margin-top: 20px;
    border-top: 1px solid #d1d5db;
    padding-top: 10px;
    color: #6b7280;
    font-size: 10px;
}

@page {
    size: A4 landscape;
    margin: 10mm;
}

@media print {
    .ap-print-page {
        min-height: auto;
        padding: 0;
        background: #ffffff;
    }

    .ap-print-toolbar {
        display: none !important;
    }

    .ap-print-document {
        width: 100%;
        border: 0;
        padding: 0;
        box-shadow: none;
    }

    .ap-print-summary-grid {
        gap: 6px;
    }

    .ap-print-summary-card {
        padding: 8px;
    }

    .ap-print-table-wrapper {
        overflow: visible;
    }

    .ap-print-page a {
        color: inherit;
        text-decoration: none;
    }
}
</style>