<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import CustomerSettlementLifecycleActions from '@/Components/Accounting/CustomerSettlementLifecycleActions.vue';
import ErpLayout from '@/Layouts/ErpLayout.vue';
import type { CustomerArAdjustmentDetail, CustomerSettlementStatus } from '@/Types/customer-settlement';
defineOptions({ layout: ErpLayout });
const props = defineProps<{ document: CustomerArAdjustmentDetail }>();
const deleting = ref(false);
const title = computed(() => props.document.adjustment_number ?? `AR Adjustment Draft #${props.document.id}`);
const money = (value: string): string => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(value));
const date = (value: string | null): string => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : '—';
const statusClass = (status: CustomerSettlementStatus): string => status === 'posted' ? 'bg-success-50 text-success-700' : status === 'reversed' || status === 'cancelled' ? 'bg-error-50 text-error-700' : 'bg-gray-100 text-gray-700';
const remove = (): void => { if (!window.confirm('Delete this AR Adjustment draft?')) return; deleting.value = true; router.delete(route('customer-ar-adjustments.destroy', props.document.id), { onFinish: () => { deleting.value = false; } }); };
</script>
<template><Head :title="title" /><div class="space-y-6">
<div class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div class="mb-2 flex gap-2 text-sm text-gray-500"><Link :href="route('customer-ar-adjustments.index')">AR Adjustments</Link><span>/</span><span>{{ title }}</span></div><div class="flex items-center gap-3"><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">{{ title }}</h1><span :class="['rounded-full px-2.5 py-1 text-xs font-medium', statusClass(document.status)]">{{ document.status_label }}</span></div><p class="mt-1 text-sm text-gray-500">{{ document.customer_name }} · {{ document.customer_code }} · Revision {{ document.revision }}</p></div><div class="flex flex-wrap gap-2"><Link :href="route('customer-ar-adjustments.index')" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm">Back</Link><Link v-if="document.can.update" :href="route('customer-ar-adjustments.edit', document.id)" class="rounded-lg border border-brand-300 px-4 py-2.5 text-sm text-brand-600">Edit</Link><button v-if="document.can.delete" :disabled="deleting" class="rounded-lg border border-error-300 px-4 py-2.5 text-sm text-error-600" @click="remove">{{ deleting ? 'Deleting...' : 'Delete' }}</button></div></div>
<div v-if="document.can.submit || document.can.return_to_draft || document.can.approve || document.can.post || document.can.cancel || document.can.reverse" class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><CustomerSettlementLifecycleActions :document-id="document.id" route-base="customer-ar-adjustments" :permissions="document.can" /></div>
<div v-if="document.cancellation_reason || document.reversal_reason" class="rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700"><strong>{{ document.status === 'reversed' ? 'Reversal' : 'Cancellation' }}</strong><p class="mt-1">{{ document.reversal_reason ?? document.cancellation_reason }}</p></div>
<div :class="['rounded-2xl border p-6', document.direction === 'debit' ? 'border-warning-200 bg-warning-50' : 'border-success-200 bg-success-50']"><p class="text-xs uppercase text-gray-500">{{ document.direction_label }} Adjustment</p><p class="mt-2 text-3xl font-semibold">{{ document.currency_code }} {{ money(document.amount) }}</p><p class="mt-2 text-sm">{{ document.direction === 'debit' ? 'Increases customer receivables.' : 'Creates customer credit.' }} Base amount {{ money(document.base_amount) }}.</p></div>
<div class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Adjustment Details</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt class="text-gray-500">Adjustment Date</dt><dd class="mt-1 font-medium">{{ date(document.adjustment_date) }}</dd></div><div><dt class="text-gray-500">Posting Date</dt><dd class="mt-1 font-medium">{{ date(document.posting_date) }}</dd></div><div><dt class="text-gray-500">Branch</dt><dd class="mt-1 font-medium">{{ document.branch?.name ?? '—' }}</dd></div><div><dt class="text-gray-500">Exchange Rate</dt><dd class="mt-1 font-medium">{{ document.exchange_rate }}</dd></div><div class="col-span-2"><dt class="text-gray-500">Offset Account</dt><dd class="mt-1 font-medium">{{ document.offset_account?.code }} — {{ document.offset_account?.name }}</dd></div></dl></div><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Reason and Notes</h2><p class="mt-4 text-sm">{{ document.reason }}</p><p v-if="document.notes" class="mt-3 whitespace-pre-line text-sm text-gray-600">{{ document.notes }}</p></div></div>
<div v-if="document.open_item" class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Customer Open Item</h2><dl class="mt-4 grid gap-4 sm:grid-cols-3 text-sm"><div><dt class="text-gray-500">Type</dt><dd class="mt-1 font-medium capitalize">{{ document.open_item.item_type.replace(/_/g, ' ') }}</dd></div><div><dt class="text-gray-500">Status</dt><dd class="mt-1 font-medium capitalize">{{ document.open_item.status.replace(/_/g, ' ') }}</dd></div><div><dt class="text-gray-500">Outstanding</dt><dd class="mt-1 font-semibold text-brand-600">{{ document.currency_code }} {{ money(document.open_item.outstanding_amount) }}</dd></div></dl></div>
<div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Accounting References</h2><dl class="mt-4 grid gap-4 md:grid-cols-2 text-sm"><div><dt class="text-gray-500">Posting Journal</dt><dd class="mt-1 break-all font-medium">{{ document.accounting_posting_reference ?? '—' }}</dd></div><div><dt class="text-gray-500">Reversal Journal</dt><dd class="mt-1 break-all font-medium">{{ document.accounting_reversal_reference ?? '—' }}</dd></div></dl></div>
</div></template>
