<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import { computed } from 'vue';
import type { CustomerRefundPrintProps } from '@/Types/customer-settlement';
const props = defineProps<CustomerRefundPrintProps>();
const title = computed(() => props.document.refund_number ?? `Customer Refund Draft #${props.document.id}`);
const money = (value: string): string => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(value));
const date = (value: string | null): string => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : '—';
const printPage = (): void => {
    window.print();
};
</script>
<template>
<Head :title="`Customer Refund ${title}`" />
<div class="page">
    <div class="screen-actions"><button type="button" @click="printPage">Print / Save PDF</button></div>
    <header><div><h1>{{ company.name }}</h1><p>{{ company.address }}</p><p>{{ company.phone }}<span v-if="company.phone && company.email"> · </span>{{ company.email }}</p></div><div class="title"><h2>CUSTOMER REFUND VOUCHER</h2><p>{{ title }}</p><strong>{{ document.status_label }}</strong></div></header>
    <section class="grid"><div><h3>Refund To</h3><p><b>{{ document.customer_name }}</b></p><p>{{ document.customer_code }}</p><p>Branch: {{ document.branch?.name ?? '—' }}</p></div><div><h3>Voucher Information</h3><dl><dt>Refund Date</dt><dd>{{ date(document.refund_date) }}</dd><dt>Posting Date</dt><dd>{{ date(document.posting_date) }}</dd><dt>Method</dt><dd>{{ document.refund_method_label }}</dd><dt>Account</dt><dd>{{ document.refund_account?.code }} — {{ document.refund_account?.name }}</dd><dt>Reference</dt><dd>{{ document.refund_reference ?? '—' }}</dd><dt>Currency / Rate</dt><dd>{{ document.currency_code }} / {{ document.exchange_rate }}</dd></dl></div></section>
    <table><thead><tr><th>#</th><th>Credit Document</th><th>Credit Type</th><th class="right">Refund Amount</th></tr></thead><tbody><tr v-for="line in document.allocations" :key="line.id"><td>{{ line.line_number }}</td><td>{{ line.credit_document_number ?? `Open Item #${line.credit_open_item_id}` }}</td><td>{{ line.credit_item_type.replace(/_/g, ' ') }}</td><td class="right">{{ money(line.amount) }}</td></tr></tbody></table>
    <section class="bottom"><div><h3>Reason</h3><p>{{ document.reason }}</p><template v-if="document.notes"><h3>Notes</h3><p class="pre">{{ document.notes }}</p></template><template v-if="document.cheque_number"><h3>Cheque</h3><p>{{ document.cheque_number }} · {{ date(document.cheque_date) }}</p></template></div><dl class="summary"><dt>Total Refund</dt><dd>{{ document.currency_code }} {{ money(document.total_amount) }}</dd><dt>Cash Base</dt><dd>{{ money(document.base_cash_amount) }}</dd><dt>Credit Base</dt><dd>{{ money(document.base_credit_amount) }}</dd><dt>Realized FX</dt><dd>{{ money(document.exchange_difference_amount) }}</dd></dl></section>
    <section v-if="document.status === 'reversed' || document.status === 'cancelled'" class="alert"><strong>{{ document.status.toUpperCase() }}</strong><p>{{ document.reversal_reason ?? document.cancellation_reason }}</p></section>
    <footer><div><span>Prepared By</span><strong>{{ document.created_by?.name ?? '—' }}</strong></div><div><span>Approved By</span><strong>{{ document.approved_by?.name ?? '—' }}</strong></div><div><span>Received By Customer</span><strong>________________________</strong></div></footer>
</div>
</template>
<style scoped>
:global(body){margin:0;background:#f3f4f6;color:#111827;font-family:Arial,Helvetica,sans-serif}.page{box-sizing:border-box;width:210mm;min-height:297mm;margin:18px auto;padding:14mm;background:#fff}.screen-actions{text-align:right;margin-bottom:16px}.screen-actions button{border:0;border-radius:8px;background:#465fff;color:#fff;padding:10px 16px}.page header{display:flex;justify-content:space-between;gap:30px;border-bottom:2px solid #111827;padding-bottom:16px}.page h1,.page h2,.page p{margin:0 0 6px}.title{text-align:right}.title strong{display:inline-block;border-radius:999px;background:#e5e7eb;padding:4px 10px;font-size:11px;text-transform:uppercase}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:24px 0}.grid h3,.bottom h3{margin:0 0 8px;font-size:11px;text-transform:uppercase;color:#4b5563}.grid p,.bottom p{font-size:12px;line-height:1.5}.grid dl{display:grid;grid-template-columns:110px 1fr;gap:6px 12px;margin:0;font-size:12px}.grid dt{color:#6b7280}.grid dd{margin:0;font-weight:600}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #d1d5db;padding:8px}th{background:#f3f4f6;text-align:left;font-size:10px;text-transform:uppercase}.right{text-align:right}.bottom{display:grid;grid-template-columns:1fr 280px;gap:24px;margin-top:24px}.summary{display:grid;grid-template-columns:1fr auto;gap:9px 16px;margin:0;font-size:12px}.summary dd{margin:0;text-align:right;font-weight:600}.summary dt:first-child,.summary dd:nth-child(2){border-top:1px solid #111827;padding-top:9px;font-size:14px}.pre{white-space:pre-line}.alert{margin-top:20px;border:2px solid #b91c1c;padding:12px;text-align:center;color:#991b1b}.alert p{font-size:12px}footer{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:55px}footer div{border-top:1px solid #111827;padding-top:8px;text-align:center}footer span,footer strong{display:block;font-size:12px}footer span{margin-bottom:5px;color:#6b7280}@media print{@page{size:A4;margin:0}:global(body){background:#fff}.page{margin:0}.screen-actions{display:none}}
</style>
