<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import CustomerSettlementLifecycleActions from '@/Components/Accounting/CustomerSettlementLifecycleActions.vue';
import ErpLayout from '@/Layouts/ErpLayout.vue';
import type { CustomerCreditApplicationDetail, CustomerSettlementStatus } from '@/Types/customer-settlement';
defineOptions({ layout: ErpLayout });
const props = defineProps<{ document: CustomerCreditApplicationDetail }>();
const deleting = ref(false);
const title = computed(() => props.document.application_number ?? `Credit Application Draft #${props.document.id}`);
const money = (value: string): string => new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 6 }).format(Number(value));
const date = (value: string | null): string => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : '—';
const statusClass = (status: CustomerSettlementStatus): string => status === 'posted' ? 'bg-success-50 text-success-700' : status === 'reversed' || status === 'cancelled' ? 'bg-error-50 text-error-700' : 'bg-gray-100 text-gray-700';
const remove = (): void => { if (!window.confirm('Delete this Credit Application draft?')) return; deleting.value = true; router.delete(route('customer-credit-applications.destroy', props.document.id), { onFinish: () => { deleting.value = false; } }); };
</script>
<template>
<Head :title="title" /><div class="space-y-6">
<div class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div class="mb-2 flex gap-2 text-sm text-gray-500"><Link :href="route('customer-credit-applications.index')" class="hover:text-brand-500">Credit Applications</Link><span>/</span><span>{{ title }}</span></div><div class="flex flex-wrap items-center gap-3"><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">{{ title }}</h1><span :class="['rounded-full px-2.5 py-1 text-xs font-medium', statusClass(document.status)]">{{ document.status_label }}</span></div><p class="mt-1 text-sm text-gray-500">{{ document.customer_name }} · {{ document.customer_code }} · Revision {{ document.revision }}</p></div><div class="flex flex-wrap gap-2"><Link :href="route('customer-credit-applications.index')" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700">Back</Link><Link v-if="document.can.update" :href="route('customer-credit-applications.edit', document.id)" class="rounded-lg border border-brand-300 px-4 py-2.5 text-sm font-medium text-brand-600">Edit</Link><button v-if="document.can.delete" :disabled="deleting" class="rounded-lg border border-error-300 px-4 py-2.5 text-sm text-error-600" @click="remove">{{ deleting ? 'Deleting...' : 'Delete' }}</button></div></div>
<div v-if="document.can.submit || document.can.return_to_draft || document.can.approve || document.can.post || document.can.cancel || document.can.reverse" class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><CustomerSettlementLifecycleActions :document-id="document.id" route-base="customer-credit-applications" :permissions="document.can" /></div>
<div v-if="document.cancellation_reason || document.reversal_reason" class="rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700"><strong>{{ document.status === 'reversed' ? 'Reversal' : 'Cancellation' }}</strong><p class="mt-1">{{ document.reversal_reason ?? document.cancellation_reason }}</p><p v-if="document.reversal_posting_date" class="mt-1 text-xs">Posting date: {{ date(document.reversal_posting_date) }}</p></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><p class="text-xs uppercase text-gray-500">Applied Amount</p><p class="mt-2 text-xl font-semibold text-brand-600">{{ document.currency_code }} {{ money(document.total_amount) }}</p></div><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><p class="text-xs uppercase text-gray-500">Receivable Base</p><p class="mt-2 text-xl font-semibold">{{ money(document.receivable_base_amount) }}</p></div><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><p class="text-xs uppercase text-gray-500">Credit Base</p><p class="mt-2 text-xl font-semibold">{{ money(document.credit_base_amount) }}</p></div><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><p class="text-xs uppercase text-gray-500">Realized FX</p><p class="mt-2 text-xl font-semibold">{{ money(document.exchange_difference_amount) }}</p></div></div>
<div class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Document Details</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt class="text-gray-500">Application Date</dt><dd class="mt-1 font-medium">{{ date(document.application_date) }}</dd></div><div><dt class="text-gray-500">Posting Date</dt><dd class="mt-1 font-medium">{{ date(document.posting_date) }}</dd></div><div><dt class="text-gray-500">Branch</dt><dd class="mt-1 font-medium">{{ document.branch?.name ?? '—' }}</dd></div><div><dt class="text-gray-500">Currency</dt><dd class="mt-1 font-medium">{{ document.currency_code }}</dd></div></dl></div><div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Reason and Notes</h2><p class="mt-4 text-sm">{{ document.reason }}</p><p v-if="document.notes" class="mt-3 whitespace-pre-line text-sm text-gray-600 dark:text-gray-300">{{ document.notes }}</p></div></div>
<div class="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900"><div class="border-b border-gray-200 p-5 dark:border-gray-800"><h2 class="text-lg font-semibold">Allocation Lines</h2></div><div class="overflow-x-auto"><table class="min-w-[1000px] divide-y divide-gray-200 dark:divide-gray-800"><thead class="bg-gray-50 dark:bg-white/[0.03]"><tr><th class="px-5 py-3 text-left text-xs uppercase text-gray-500">#</th><th class="px-5 py-3 text-left text-xs uppercase text-gray-500">Receivable</th><th class="px-5 py-3 text-left text-xs uppercase text-gray-500">Credit</th><th class="px-5 py-3 text-right text-xs uppercase text-gray-500">Amount</th><th class="px-5 py-3 text-right text-xs uppercase text-gray-500">Receivable Base</th><th class="px-5 py-3 text-right text-xs uppercase text-gray-500">Credit Base</th><th class="px-5 py-3 text-right text-xs uppercase text-gray-500">FX</th><th class="px-5 py-3 text-left text-xs uppercase text-gray-500">Status</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800"><tr v-for="line in document.lines" :key="line.id"><td class="px-5 py-4 text-sm">{{ line.line_number }}</td><td class="px-5 py-4 text-sm font-medium">{{ line.receivable_document_number ?? `Open Item #${line.receivable_open_item_id}` }}</td><td class="px-5 py-4"><p class="text-sm font-medium">{{ line.credit_document_number ?? `Open Item #${line.credit_open_item_id}` }}</p><p class="text-xs text-gray-500">{{ line.credit_item_type.replace(/_/g, ' ') }}</p></td><td class="px-5 py-4 text-right text-sm font-semibold">{{ money(line.amount) }}</td><td class="px-5 py-4 text-right text-sm">{{ money(line.receivable_base_amount) }}</td><td class="px-5 py-4 text-right text-sm">{{ money(line.credit_base_amount) }}</td><td class="px-5 py-4 text-right text-sm">{{ money(line.exchange_difference_amount) }}</td><td class="px-5 py-4 text-sm capitalize">{{ line.status.replace(/_/g, ' ') }}</td></tr></tbody></table></div></div>
<div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="text-lg font-semibold">Accounting References</h2><dl class="mt-4 grid gap-4 md:grid-cols-2 text-sm"><div><dt class="text-gray-500">Posting Journal</dt><dd class="mt-1 break-all font-medium">{{ document.accounting_posting_reference ?? '—' }}</dd></div><div><dt class="text-gray-500">Reversal Journal</dt><dd class="mt-1 break-all font-medium">{{ document.accounting_reversal_reference ?? '—' }}</dd></div></dl></div>
</div>
</template>
